import { writeFileSync } from 'node:fs'
import { deflateRawSync } from 'node:zlib'

const CRC_TABLE = (() => {
  const table = new Uint32Array(256)
  for (let i = 0; i < 256; i++) {
    let c = i
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    table[i] = c >>> 0
  }
  return table
})()

export function crc32(bytes: Uint8Array): number {
  let c = 0xffffffff
  for (const byte of bytes) c = CRC_TABLE[(c ^ byte) & 0xff]! ^ (c >>> 8)
  return (c ^ 0xffffffff) >>> 0
}

export function concatBytes(parts: Uint8Array[]): Uint8Array {
  const total = parts.reduce((n, p) => n + p.length, 0)
  const out = new Uint8Array(total)
  let at = 0
  for (const part of parts) {
    out.set(part, at)
    at += part.length
  }
  return out
}

export type ZipInput = { name: string; data: string | Uint8Array; deflate?: boolean }

export function writeZip(path: string, entries: ZipInput[]): void {
  const encoder = new TextEncoder()
  const body: Uint8Array[] = []
  const central: Uint8Array[] = []
  let offset = 0

  for (const entry of entries) {
    const raw = typeof entry.data === 'string' ? encoder.encode(entry.data) : entry.data
    const method = entry.deflate ? 8 : 0
    const stored = entry.deflate ? new Uint8Array(deflateRawSync(raw)) : raw
    const name = encoder.encode(entry.name)
    const checksum = crc32(raw)

    const local = new Uint8Array(30 + name.length)
    const lv = new DataView(local.buffer)
    lv.setUint32(0, 0x04034b50, true)
    lv.setUint16(4, 20, true)
    lv.setUint16(8, method, true)
    lv.setUint32(14, checksum, true)
    lv.setUint32(18, stored.length, true)
    lv.setUint32(22, raw.length, true)
    lv.setUint16(26, name.length, true)
    local.set(name, 30)
    body.push(local, stored)

    const cd = new Uint8Array(46 + name.length)
    const cv = new DataView(cd.buffer)
    cv.setUint32(0, 0x02014b50, true)
    cv.setUint16(4, 20, true)
    cv.setUint16(6, 20, true)
    cv.setUint16(10, method, true)
    cv.setUint32(16, checksum, true)
    cv.setUint32(20, stored.length, true)
    cv.setUint32(24, raw.length, true)
    cv.setUint16(28, name.length, true)
    cv.setUint32(42, offset, true)
    cd.set(name, 46)
    central.push(cd)

    offset += local.length + stored.length
  }

  const cdBytes = concatBytes(central)
  const eocd = new Uint8Array(22)
  const ev = new DataView(eocd.buffer)
  ev.setUint32(0, 0x06054b50, true)
  ev.setUint16(8, entries.length, true)
  ev.setUint16(10, entries.length, true)
  ev.setUint32(12, cdBytes.length, true)
  ev.setUint32(16, offset, true)

  writeFileSync(path, concatBytes([...body, cdBytes, eocd]))
}

/** A slice_info.config carrying the given header-item keys, values deliberately junk. */
export function sliceInfo(keys: string[]): string {
  const items = keys.map((key) => `    <header_item key="${key}" value="whatever"/>`).join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>\n<config>\n  <header>\n${items}\n  </header>\n  <plate>\n    <metadata key="printer_model_id" value="Anycubic Kobra X"/>\n  </plate>\n</config>\n`
}

const MODEL_XML = '<?xml version="1.0"?><model unit="millimeter"><resources/></model>'

export function curaProject(path: string, thumbnail?: Uint8Array): void {
  writeZip(path, [
    { name: '[Content_Types].xml', data: '<Types/>' },
    { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
    { name: 'Cura/plugin_metadata.json', data: '{}' },
    { name: 'Cura/preferences.cfg', data: '[general]' },
    ...(thumbnail ? [{ name: 'Metadata/thumbnail.png', data: thumbnail }] : []),
  ])
}

export function prusaProject(path: string, thumbnail?: Uint8Array): void {
  writeZip(path, [
    { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
    { name: 'Metadata/Slic3r_PE.config', data: '; generated by PrusaSlicer' },
    { name: 'Metadata/Slic3r_PE_model.config', data: '<config/>' },
    ...(thumbnail ? [{ name: 'Metadata/thumbnail.png', data: thumbnail }] : []),
  ])
}

/** Anycubic, Bambu and Orca share this layout exactly; only the header keys differ. */
export function bambuLineageProject(
  path: string,
  headerKeys: string[],
  thumbnail?: Uint8Array,
): void {
  writeZip(path, [
    { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
    { name: 'Metadata/project_settings.config', data: '{"version": "02.08.02.61"}' },
    { name: 'Metadata/model_settings.config', data: '<config/>' },
    { name: 'Metadata/slice_info.config', data: sliceInfo(headerKeys) },
    ...(thumbnail
      ? [
          { name: 'Metadata/plate_1.png', data: thumbnail },
          { name: 'Metadata/plate_1_small.png', data: thumbnail },
          { name: 'Metadata/top_1.png', data: thumbnail },
        ]
      : []),
  ])
}

/** Saved but never sliced, so slice_info.config was never written (spec 3.4, rule 4). */
export function unslicedBambuProject(path: string): void {
  writeZip(path, [
    { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
    { name: 'Metadata/project_settings.config', data: '{"version": "02.06.00.51"}' },
    { name: 'Metadata/model_settings.config', data: '<config/>' },
  ])
}

export function plainMesh3mf(path: string): void {
  writeZip(path, [
    { name: '[Content_Types].xml', data: '<Types/>' },
    { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
  ])
}
