import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { entryDiff, entryHash } from '../src/files/entry-hash.ts'
import { assert, test } from './harness.ts'
import { writeZip, type ZipInput } from './fixtures/make-3mf.ts'
import { patchZipHeaders } from './fixtures/patch-zip.ts'

const MODEL_XML = '<?xml version="1.0"?><model unit="millimeter"><resources/></model>'

function withDir(run: (dir: string) => void | Promise<void>): Promise<void> {
  const dir = mkdtempSync(join(tmpdir(), 'spm-hash-'))
  return Promise.resolve(run(dir)).finally(() => rmSync(dir, { recursive: true, force: true }))
}

/** The wall-clock DOS stamp the three Bambu-lineage slicers write on every save. */
function stampTimes(path: string, time: number, date: number): void {
  patchZipHeaders(path, ({ file, centralAt, localAt }) => {
    file.setUint16(centralAt + 12, time, true)
    file.setUint16(centralAt + 14, date, true)
    file.setUint16(localAt + 10, time, true)
    file.setUint16(localAt + 12, date, true)
  })
}

const PROJECT: ZipInput[] = [
  { name: '[Content_Types].xml', data: '<Types/>' },
  { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
  { name: 'Metadata/project_settings.config', data: '{"layer_height":"0.2"}' },
  { name: 'Metadata/plate_1.png', data: new Uint8Array([1, 2, 3, 4]) },
]

const prusaConfig = (at: string) =>
  `; generated by PrusaSlicer 2.9.6 on 2026-08-28 at ${at} UTC\n; layer_height = 0.2\n; fill_density = 15%\n`

test('two saves of identical content with different ZIP timestamps hash equal', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    writeZip(a, PROJECT)
    writeZip(b, PROJECT)
    stampTimes(a, 0x5c2b, 0x5d1c)
    stampTimes(b, 0x61f0, 0x5d1d)
    // The container really did change: this is the measured failure of a whole-file hash.
    assert.notDeepEqual([...new Uint8Array(readFileSync(a))], [...new Uint8Array(readFileSync(b))])

    assert.equal(entryHash(a), entryHash(b))
    assert.deepEqual(entryDiff(a, b), { added: [], removed: [], changed: [] })
  }))

test('entry order and compression method do not move the hash', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    writeZip(a, [
      { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
      { name: 'Metadata/notes.txt', data: 'hello' },
    ])
    writeZip(b, [
      { name: 'Metadata/notes.txt', data: 'hello', deflate: true },
      { name: '3D/3dmodel.model', data: MODEL_XML },
    ])

    assert.equal(entryHash(a), entryHash(b))
  }))

test('two Slic3r_PE.configs differing only in the generated-on line hash equal', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    writeZip(a, [
      { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
      { name: 'Metadata/Slic3r_PE.config', data: prusaConfig('09:27:30') },
    ])
    writeZip(b, [
      { name: '3D/3dmodel.model', data: MODEL_XML, deflate: true },
      { name: 'Metadata/Slic3r_PE.config', data: prusaConfig('09:28:00') },
    ])

    assert.equal(entryHash(a), entryHash(b))
    assert.deepEqual(entryDiff(a, b), { added: [], removed: [], changed: [] })
  }))

test('a setting changed below the generated-on line still hashes differently', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    writeZip(a, [{ name: 'Metadata/Slic3r_PE.config', data: prusaConfig('09:27:30') }])
    writeZip(b, [
      {
        name: 'Metadata/Slic3r_PE.config',
        data: prusaConfig('09:28:00').replace('0.2', '0.3'),
      },
    ])

    assert.notEqual(entryHash(a), entryHash(b))
    assert.deepEqual(entryDiff(a, b), {
      added: [],
      removed: [],
      changed: ['Metadata/Slic3r_PE.config'],
    })
  }))

test('only the leading generated-on line is excluded, and only in that one part', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    // The stamp text as a *second* line. What keeps it counted is not the regex's `^` — a probe
    // removing that anchor left every test green — but `hashableBytes` slicing the first line off
    // before it matches at all. Written down because the anchor is the tempting explanation.
    const withSecondLine = (at: string) =>
      `; PrusaSlicer config\n; generated by PrusaSlicer 2.9.6 on 2026-08-28 at ${at} UTC\n`
    writeZip(a, [{ name: 'Metadata/Slic3r_PE.config', data: withSecondLine('09:27:30') }])
    writeZip(b, [{ name: 'Metadata/Slic3r_PE.config', data: withSecondLine('09:28:00') }])
    assert.notEqual(entryHash(a), entryHash(b))

    // And the exclusion is keyed on the entry name: the same text anywhere else counts.
    const c = join(dir, 'c.3mf')
    const d = join(dir, 'd.3mf')
    writeZip(c, [{ name: 'Metadata/other.config', data: prusaConfig('09:27:30') }])
    writeZip(d, [{ name: 'Metadata/other.config', data: prusaConfig('09:28:00') }])
    assert.notEqual(entryHash(c), entryHash(d))
  }))

test('one changed byte anywhere hashes differently', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    writeZip(a, PROJECT)
    const before = entryHash(a)

    for (const changed of [
      { name: 'Metadata/project_settings.config', data: '{"layer_height":"0.3"}' },
      { name: 'Metadata/plate_1.png', data: new Uint8Array([1, 2, 3, 5]) },
      { name: '3D/3dmodel.model', data: `${MODEL_XML} `, deflate: true },
    ]) {
      const b = join(dir, `b-${changed.name.replace(/\W/g, '_')}.3mf`)
      writeZip(
        b,
        PROJECT.map((entry) => (entry.name === changed.name ? changed : entry)),
      )
      assert.notEqual(entryHash(b), before, changed.name)
      assert.deepEqual(entryDiff(a, b), { added: [], removed: [], changed: [changed.name] })
    }
  }))

test('entryDiff names what was added and removed, and reports nothing about what is inside', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    writeZip(a, PROJECT)
    writeZip(b, [
      ...PROJECT.filter((entry) => entry.name !== 'Metadata/plate_1.png'),
      { name: 'Metadata/cut_information.xml', data: '<objects/>' },
    ])

    assert.deepEqual(entryDiff(a, b), {
      added: ['Metadata/cut_information.xml'],
      removed: ['Metadata/plate_1.png'],
      changed: [],
    })
  }))

test('the name and the content are framed, so a shifted boundary is not a collision', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    // Concatenating name + bytes without a length makes these two archives identical to hash.
    writeZip(a, [{ name: 'a', data: 'bc' }])
    writeZip(b, [{ name: 'ab', data: 'c' }])

    assert.notEqual(entryHash(a), entryHash(b))
  }))

test('a file that is not a zip is hashed as plain bytes, and diffed under its own name', () =>
  withDir((dir) => {
    mkdirSync(join(dir, 'returned'))
    const launched = join(dir, 'cube.stl')
    const unchanged = join(dir, 'returned', 'cube.stl')
    const changed = join(dir, 'returned', 'changed.stl')
    writeFileSync(launched, 'solid cube\nendsolid cube\n')
    writeFileSync(unchanged, 'solid cube\nendsolid cube\n')
    writeFileSync(changed, 'solid cube\nendsolid CUBE\n')

    assert.equal(entryHash(launched), entryHash(unchanged))
    assert.notEqual(entryHash(launched), entryHash(changed))
    // The case task 5 has: the launch directory's copy of the same file, compared to the source.
    assert.deepEqual(entryDiff(launched, unchanged), { added: [], removed: [], changed: [] })
    writeFileSync(unchanged, readFileSync(changed))
    assert.deepEqual(entryDiff(launched, unchanged), {
      added: [],
      removed: [],
      changed: ['cube.stl'],
    })
    // Two different basenames read as one file gone and another arrived, which is what they are.
    assert.deepEqual(entryDiff(launched, changed), {
      added: ['changed.stl'],
      removed: ['cube.stl'],
      changed: [],
    })
  }))

test('an empty file and an empty archive both hash without throwing', () =>
  withDir((dir) => {
    const empty = join(dir, 'empty.stl')
    writeFileSync(empty, '')
    const archive = join(dir, 'empty.3mf')
    writeZip(archive, [])

    // Both come out as SHA-256 over zero bytes, and they are therefore equal. Recorded rather
    // than asserted away: the two hash spaces meet only at nothing-at-all, and change detection
    // only ever compares a path against its own earlier self.
    assert.equal(entryHash(empty).length, 64)
    assert.equal(entryHash(archive), entryHash(empty))
  }))

test('the hash is stable across repeated reads of the same file', () =>
  withDir((dir) => {
    const path = join(dir, 'a.3mf')
    writeZip(path, PROJECT)
    assert.equal(entryHash(path), entryHash(path))
  }))

test('an ordinary leading comment in Slic3r_PE.config is not mistaken for the stamp', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    // `Slic3r_PE.config` is nothing but `; key = value` lines, so a pattern loose enough to mean
    // "any leading comment" would hide the first setting in the file every time it changed.
    writeZip(a, [
      { name: 'Metadata/Slic3r_PE.config', data: '; layer_height = 0.2\n; fill = 15%\n' },
    ])
    writeZip(b, [
      { name: 'Metadata/Slic3r_PE.config', data: '; layer_height = 0.3\n; fill = 15%\n' },
    ])

    assert.notEqual(entryHash(a), entryHash(b))
    assert.deepEqual(entryDiff(a, b).changed, ['Metadata/Slic3r_PE.config'])
  }))

test('a stamp with anything appended after UTC is left in rather than guessed at', () =>
  withDir((dir) => {
    const a = join(dir, 'a.3mf')
    const b = join(dir, 'b.3mf')
    // Not a measured line — the point is the direction of the error. An unrecognised first line
    // counts towards the hash, so an unexpected format costs a spurious "this changed" and never
    // a missed one.
    const stamped = (at: string) => `; generated by PrusaSlicer 2.9.6 at ${at} UTC (dev)\n; x = 1\n`
    writeZip(a, [{ name: 'Metadata/Slic3r_PE.config', data: stamped('09:27:30') }])
    writeZip(b, [{ name: 'Metadata/Slic3r_PE.config', data: stamped('09:28:00') }])

    assert.notEqual(entryHash(a), entryHash(b))
  }))
