import type { AppError } from '@spm/contract/errors.ts'
import { parseStl } from '../src/previews/mesh/stl.ts'
import { assert, test } from './harness.ts'

// One coordinate (0.1) is deliberately not exactly representable in float32: 0 and 1 alone
// would round-trip identically through both encodings even if one path had a float64/float32
// rounding divergence, so this fixture couldn't have caught that class of bug.
const CUBE_VERTICES: [number, number, number][] = [
  [0.1, 0, 0],
  [1, 0, 0],
  [1, 1, 0],
  [0, 1, 0],
  [0, 0, 1],
  [1, 0, 1],
  [1, 1, 1],
  [0, 1, 1],
]

const CUBE_FACES: [number, number, number][] = [
  [0, 1, 2],
  [0, 2, 3],
  [4, 5, 6],
  [4, 6, 7],
  [0, 1, 5],
  [0, 5, 4],
  [3, 2, 6],
  [3, 6, 7],
  [0, 4, 7],
  [0, 7, 3],
  [1, 5, 6],
  [1, 6, 2],
]

/** Each element is one triangle's 9 flattened vertex coordinates. */
function cubeTriangles(): number[][] {
  return CUBE_FACES.map((face) => face.flatMap((i) => CUBE_VERTICES[i]!))
}

function binaryStl(triangles: number[][]): Uint8Array {
  const out = new Uint8Array(84 + triangles.length * 50)
  const view = new DataView(out.buffer)
  view.setUint32(80, triangles.length, true)
  let offset = 84
  for (const triangle of triangles) {
    offset += 12 // facet normal left as zero; parseStl ignores it
    for (const value of triangle) {
      view.setFloat32(offset, value, true)
      offset += 4
    }
    offset += 2 // attribute byte count
  }
  return out
}

function asciiStl(triangles: number[][], solidName = 'cube'): Uint8Array {
  const lines = [`solid ${solidName}`]
  for (const t of triangles) {
    lines.push('  facet normal 0 0 0', '    outer loop')
    for (let i = 0; i < 3; i++)
      lines.push(`      vertex ${t[i * 3]} ${t[i * 3 + 1]} ${t[i * 3 + 2]}`)
    lines.push('    endloop', '  endfacet')
  }
  lines.push(`endsolid ${solidName}`)
  // CRLF, to exercise the "tolerate CRLF" requirement rather than assuming Unix line endings.
  return new TextEncoder().encode(lines.join('\r\n'))
}

function withPrefix(prefix: number[], bytes: Uint8Array): Uint8Array {
  const out = new Uint8Array(prefix.length + bytes.length)
  out.set(prefix, 0)
  out.set(bytes, prefix.length)
  return out
}

const validation = (e: unknown): boolean => (e as AppError).code === 'Validation'

test('binary and ASCII encodings of the same cube parse to equal positions', () => {
  const triangles = cubeTriangles()
  const fromBinary = parseStl(binaryStl(triangles))
  const fromAscii = parseStl(asciiStl(triangles))
  assert.equal(fromBinary.triangleCount, 12)
  assert.equal(fromAscii.triangleCount, 12)
  assert.deepEqual(fromAscii.positions, fromBinary.positions)
})

test('a binary STL whose header spells "solid" is still parsed as binary, not ASCII', () => {
  const triangles = cubeTriangles()
  const bytes = binaryStl(triangles)
  // Overwrites only the 80-byte free-form header, leaving the triangle count (bytes 80-83)
  // and all triangle data untouched, so the file is still a well-formed binary STL.
  new TextEncoder().encodeInto('solid cube, generated by ExampleSlicer', bytes.subarray(0, 80))
  const mesh = parseStl(bytes)
  assert.equal(mesh.triangleCount, 12)
  assert.deepEqual(mesh.positions, parseStl(binaryStl(triangles)).positions)
})

test('ASCII parsing tolerates CRLF and irregular whitespace', () => {
  const bytes = new TextEncoder().encode(
    'solid x\r\n  facet normal 0 0 0\r\n    outer loop\r\n' +
      '      vertex   0   0   0\r\n' +
      '      vertex 1 0 0\r\n' +
      '      vertex 1 1    0\r\n' +
      '    endloop\r\n  endfacet\r\nendsolid x\r\n',
  )
  const mesh = parseStl(bytes)
  assert.equal(mesh.triangleCount, 1)
  assert.deepEqual(Array.from(mesh.positions), [0, 0, 0, 1, 0, 0, 1, 1, 0])
})

test('a binary STL with a NaN coordinate is rejected', () => {
  const bytes = binaryStl(cubeTriangles())
  // Byte 96 is the first vertex-coordinate float of triangle 0 (offset 84 + 12-byte normal).
  new DataView(bytes.buffer).setFloat32(96, NaN, true)
  assert.throws(() => parseStl(bytes), validation)
})

test('an ASCII STL prefixed with a UTF-8 BOM still parses (length triggers binary detection)', () => {
  const bytes = withPrefix([0xef, 0xbb, 0xbf], asciiStl(cubeTriangles()))
  assert.ok(bytes.length >= 84)
  assert.equal(parseStl(bytes).triangleCount, 12)
})

test('an ASCII STL prefixed with a blank line still parses (length triggers binary detection)', () => {
  const bytes = withPrefix([0x0a], asciiStl(cubeTriangles()))
  assert.ok(bytes.length >= 84)
  assert.equal(parseStl(bytes).triangleCount, 12)
})

test('an ASCII STL prefixed with leading spaces still parses (length triggers binary detection)', () => {
  const bytes = withPrefix([0x20, 0x20, 0x20], asciiStl(cubeTriangles()))
  assert.ok(bytes.length >= 84)
  assert.equal(parseStl(bytes).triangleCount, 12)
})

test('a truncated binary STL is rejected', () => {
  const bytes = binaryStl(cubeTriangles())
  assert.throws(() => parseStl(bytes.subarray(0, bytes.length - 10)), validation)
})

test('a binary STL with trailing bytes past its declared triangle count is rejected', () => {
  const bytes = binaryStl(cubeTriangles())
  const withGarbage = new Uint8Array(bytes.length + 5)
  withGarbage.set(bytes)
  assert.throws(() => parseStl(withGarbage), validation)
})

test('a binary STL with zero triangles is rejected', () => {
  assert.throws(() => parseStl(binaryStl([])), validation)
})

test('an ASCII STL with no vertices is rejected', () => {
  const bytes = new TextEncoder().encode('solid empty\nendsolid empty\n')
  assert.throws(() => parseStl(bytes), validation)
})

test('an ASCII STL whose facet vertex count is not a multiple of 3 is rejected', () => {
  const bytes = new TextEncoder().encode(
    'solid x\nfacet normal 0 0 0\nouter loop\nvertex 0 0 0\nvertex 1 0 0\nendloop\nendfacet\nendsolid x\n',
  )
  assert.throws(() => parseStl(bytes), validation)
})

test('an ASCII STL with a non-numeric vertex coordinate is rejected', () => {
  const bytes = new TextEncoder().encode(
    'solid x\nfacet normal 0 0 0\nouter loop\nvertex a b c\nvertex 1 0 0\nvertex 1 1 0\nendloop\nendfacet\nendsolid x\n',
  )
  assert.throws(() => parseStl(bytes), validation)
})
