import { createHash, type Hash } from 'node:crypto'
import { closeSync, openSync, readSync } from 'node:fs'
import { basename } from 'node:path'
import { openZip } from './zip.ts'

/**
 * "Did this file come back changed?", answered for a `.3mf` a slicer has had.
 *
 * **Neither a whole-file hash nor mtime is a valid answer**, and both were measured failing:
 *
 * - All four in-place savers produce a different container hash for byte-identical content.
 *   Anycubic, Bambu and Orca because they write wall-clock ZIP timestamps; PrusaSlicer because it
 *   stamps `; generated by PrusaSlicer 2.9.6 on … at HH:MM:SS UTC` into the *payload* of
 *   `Metadata/Slic3r_PE.config`. Only PrusaSlicer's reason survives a hash of the decompressed
 *   entries, which is why exactly one exclusion is needed here and why the other three need none.
 *   Cura alone is byte-stable — and Cura is the one slicer that never writes back at all.
 * - mtime fails in both directions: the four in-place savers skip the write entirely when nothing
 *   is dirty, and Cura's re-save of unchanged content moved it. It is a *hint* about when to
 *   bother hashing, never an answer.
 *
 * So the hash is over the decompressed entries, and it ignores local and central headers,
 * timestamps, the compression method and entry order.
 *
 * **Memory.** An entry is decompressed into one buffer, so the peak is the largest single entry,
 * not the archive. That is the same trade `readZipEntryBytes` already makes and it is right for
 * the files this runs on — a launch directory holds one project `.3mf`, measured at 24 KB to
 * 144 KB. A library's largest *model part* is 674 MB, and hashing one of those here would cost
 * that; nothing in subsystem D does, and if something ever must, this is the line to revisit.
 */

/** Read size for the non-ZIP path, which streams rather than allocating the file. */
const READ_CHUNK_BYTES = 1 << 20

const SLIC3R_CONFIG = 'Metadata/Slic3r_PE.config'

/**
 * The line PrusaSlicer restamps on every save, measured as
 * `; generated by PrusaSlicer 2.9.6 on 2026-08-28 at 09:27:30 UTC`.
 *
 * Only ever tested against the part's **first line**, which is where the anchoring actually comes
 * from — `hashableBytes` slices the line off before matching, so `^` and `$` here are about the
 * shape of that one line and not about finding it. `$` earns its place: it is what keeps the
 * pattern from being "any leading comment". The rest of `Slic3r_PE.config` is `; key = value`
 * comment lines that must keep counting, and a looser pattern would silently swallow the first
 * setting in the file. Erring towards *not* excluding is the safe direction: the cost is a
 * spurious "this changed", never a missed one.
 */
const GENERATED_ON = /^; generated by .* at .*UTC$/

export type EntryDiff = {
  added: string[]
  removed: string[]
  changed: string[]
}

/**
 * SHA-256 over, for each entry in **name order**: the entry name, then the entry's **decompressed**
 * bytes, with the generated-on line of `Metadata/Slic3r_PE.config` excluded.
 *
 * For a file whose **central directory does not parse** — an `.stl`, an `.obj`, a `.3mf` truncated
 * mid-write — it is a plain SHA-256 of the file's bytes. Nothing measured argues against that; it
 * is the fallback it looks like.
 *
 * The fallback is keyed on that parse and nothing else, which is narrower than "not a ZIP" and
 * narrower than "mid-write". A file whose directory parses but whose payload does not — a
 * half-flushed entry behind an intact directory, an unsupported compression method — **throws**
 * rather than falling back, and so does a file that cannot be read at all. Task 5's settle window
 * is what that case is for: an exception there means "not settled yet", and turning it into a
 * plausible hash of half a file would defeat exactly that.
 *
 * Name and content are length-framed rather than simply concatenated. Without framing an archive
 * holding `{a: "bc"}` hashes identically to one holding `{ab: "c"}`, which is a silent
 * "nothing changed" on a file where everything did.
 */
export function entryHash(path: string): string {
  const hash = createHash('sha256')
  const zip = openReadableZip(path)
  if (zip === null) {
    hashFileBytes(path, hash)
    return hash.digest('hex')
  }
  try {
    const encoder = new TextEncoder()
    for (const entry of [...zip.entries].sort(byName)) {
      const name = encoder.encode(entry.name)
      framed(hash, name)
      framed(hash, hashableBytes(entry.name, zip.read(entry)))
    }
  } finally {
    zip.close()
  }
  return hash.digest('hex')
}

/**
 * Which entries were added, removed, or changed between two files, by name and over decompressed
 * content — with the same generated-on exclusion `entryHash` applies.
 *
 * It reports **that** an entry changed, never which setting inside it changed. A slicer's
 * `project_settings.config` is thousands of keys and a round trip rewrites an unknowable number of
 * them; naming one would be an assertion about a file this code has not read.
 *
 * A file that is not a readable ZIP is treated as a one-entry archive under its own basename, so
 * an `.stl` that came back changed reports `changed: ['cube.stl']` rather than nothing at all.
 */
export function entryDiff(a: string, b: string): EntryDiff {
  const left = entryDigests(a)
  const right = entryDigests(b)
  const added: string[] = []
  const removed: string[] = []
  const changed: string[] = []
  for (const [name, digest] of left) {
    const other = right.get(name)
    if (other === undefined) removed.push(name)
    else if (other !== digest) changed.push(name)
  }
  for (const name of right.keys()) if (!left.has(name)) added.push(name)
  return { added: added.sort(), removed: removed.sort(), changed: changed.sort() }
}

/** One digest per entry, keyed by name. The non-ZIP fallback is a single entry; see `entryDiff`. */
function entryDigests(path: string): Map<string, string> {
  const digests = new Map<string, string>()
  const zip = openReadableZip(path)
  if (zip === null) {
    const hash = createHash('sha256')
    hashFileBytes(path, hash)
    digests.set(basename(path), hash.digest('hex'))
    return digests
  }
  try {
    for (const entry of zip.entries) {
      const hash = createHash('sha256')
      hash.update(hashableBytes(entry.name, zip.read(entry)))
      // Last one wins on a duplicated name, which is what a reader extracting the archive would
      // also end up with. Nothing generates them; the map simply cannot hold both.
      digests.set(entry.name, hash.digest('hex'))
    }
  } finally {
    zip.close()
  }
  return digests
}

/**
 * The bytes of one entry as they count towards a hash: everything, except the leading
 * generated-on line of `Metadata/Slic3r_PE.config`.
 *
 * Done on the bytes rather than on decoded text, so an entry that is not valid UTF-8 is never
 * round-tripped through a decoder that would replace what it could not read.
 */
function hashableBytes(name: string, bytes: Uint8Array): Uint8Array {
  if (name !== SLIC3R_CONFIG) return bytes
  const newline = bytes.indexOf(0x0a)
  const end = newline === -1 ? bytes.length : newline
  const first = new TextDecoder().decode(bytes.subarray(0, end)).replace(/\r$/, '')
  if (!GENERATED_ON.test(first)) return bytes
  return newline === -1 ? bytes.subarray(0, 0) : bytes.subarray(newline + 1)
}

function byName(a: { name: string }, b: { name: string }): number {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0
}

/**
 * An 8-byte little-endian length before the bytes it describes, so the boundary between an entry's
 * name and its content is part of the hash rather than something the reader has to guess.
 */
function framed(hash: Hash, bytes: Uint8Array): void {
  const length = new Uint8Array(8)
  new DataView(length.buffer).setBigUint64(0, BigInt(bytes.byteLength), true)
  hash.update(length)
  hash.update(bytes)
}

/** `null` when the path is not a readable ZIP, which is the plain-SHA-256 case. */
function openReadableZip(path: string): ReturnType<typeof openZip> | null {
  try {
    return openZip(path)
  } catch {
    return null
  }
}

function hashFileBytes(path: string, hash: Hash): void {
  const fd = openSync(path, 'r')
  try {
    const buffer = new Uint8Array(READ_CHUNK_BYTES)
    for (;;) {
      const read = readSync(fd, buffer, 0, buffer.length, null)
      if (read === 0) break
      hash.update(buffer.subarray(0, read))
    }
  } finally {
    closeSync(fd)
  }
}
